NUMPY

In [7]:
import numpy as np

ARRAY

In [4]:
a = np.array([1,2,4])
a

array([1, 2, 4])

In [8]:
tinggi = [110, 1.8, 1.9]
berat = [55, 75, 90]
np_tinggi = np.array(tinggi)
np_berat = np.array(berat)

np_berat/np_tinggi

array([ 0.5       , 41.66666667, 47.36842105])

In [7]:
np.empty(3)

array([1.01646135e-311, 8.01091099e-307, 4.99006302e-322])

0-D / Skalar

In [10]:
arr = np.array (4)
print(arr)

4


1-D/Vektor

In [12]:
a = np.array([1,2,4])
print(a)

[1 2 4]


2-D/Matriks

In [20]:
a = np.array([[1,2,4], 
              [4,5,6]])
print(a)

[[1 2 4]
 [4 5 6]]


Lebih Dari 2D

In [18]:
a = np.array([[[1,2,4], 
              [4,5,6]],
              [[1,2,4], 
              [4,5,6]],
              [[1,2,4], 
              [4,5,6]]])
print(a)

[[[1 2 4]
  [4 5 6]]

 [[1 2 4]
  [4 5 6]]

 [[1 2 4]
  [4 5 6]]]


RESHAPE

In [26]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [28]:
matriks = a.reshape(6,1)
print(matriks)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


Index and Slicing

In [12]:
arr = np.array([[2, 3, 7, 8, 9], [1, 3, 6, 8,7]])
print(arr[1:4, 1])

[3]


In [16]:
print(arr[0:4, 4])

[9 7]


In [18]:
print(arr[0:4])

[[2 3 7 8 9]
 [1 3 6 8 7]]


Vstack dan Hstack

In [19]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])

np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [20]:
a_1 = np.array([[1, 1],
                [2, 2]])
a_2 = np.array([[3, 3],
                [4, 4]])

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

Mengubah 1-D jadi 3-D

In [21]:
data_1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [28]:
new_arr = data_1.reshape (2,2,-1)
print(new_arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Cek Data

In [30]:
#cek berapa dimensi np tersebut
new_arr.ndim

3

In [31]:
#cek kombinasi yg digunakan
new_arr.shape

(2, 2, 3)

Function

In [34]:
def convert(fahr):
    cels=fahr * 1.8 + 32.0
    return cels
print(convert(32))

89.6


In [44]:
def convert(fahr,kelv):
    cels=fahr * 1.8 + 32.0
    cels2 = kelv - 273.15
    return cels, cels2
print("Temperature in celcius (C) =", convert(32,30))


Temperature in celcius (C) = (89.6, -243.14999999999998)


In [46]:
def temp_converter(ftemp):
    ctemp = (ftemp-32)*(5/9)
    ktemp = ctemp + 273.15
    return [ftemp, ctemp, ktemp]

print(temp_converter(72))

[72, 22.22222222222222, 295.3722222222222]


In [50]:
def sum(numbers):
    total = 0
    for x in numbers:
        total += x
    return total

print(sum(1,2,3))

TypeError: sum() takes 1 positional argument but 3 were given

In [54]:
def myfunc():
    st='jojon'
    y=35
    return st,y
#a= myfunc()
#print(a[0])

#a,b = myfunc()
#print(a)

myfunc()[0]

jojon


'jojon'